<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <PackageId>Chillipommes.PommesTimer</PackageId>
        <Authors>Chillipommes</Authors>
        <PackageLicenseFile>LICENSE.txt</PackageLicenseFile>
        <PackageRequireLicenseAcceptance>True</PackageRequireLicenseAcceptance>
        <LangVersion>default</LangVersion>
        <Version>1.0.3</Version>

    </PropertyGroup>

    <ItemGroup>
      <None Include="..\..\LICENSE.txt">
        <Pack>True</Pack>
        <PackagePath>\</PackagePath>
      </None>
    </ItemGroup>






</Project>
